<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home' => [[], ['_controller' => 'App\\Controller\\WeatherController::index'], [], [['text', '/']], [], []],
    'show_weather' => [['city'], ['_controller' => 'App\\Controller\\WeatherController::showWeather'], [], [['variable', '/', '[^/]++', 'city', true]], [], []],
];
