<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzcSw1D\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzcSw1D/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIzcSw1D.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIzcSw1D\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIzcSw1D\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IzcSw1D',
    'container.build_id' => '07e56f3f',
    'container.build_time' => 1591974497,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzcSw1D');
